package map

import com.github.ocraft.s2client.protocol.data.Units

val mineralFieldTypes = setOf(
    Units.NEUTRAL_BATTLE_STATION_MINERAL_FIELD,
    Units.NEUTRAL_BATTLE_STATION_MINERAL_FIELD750,
    Units.NEUTRAL_LAB_MINERAL_FIELD,
    Units.NEUTRAL_LAB_MINERAL_FIELD750,
    Units.NEUTRAL_MINERAL_FIELD,
    Units.NEUTRAL_MINERAL_FIELD450,
    Units.NEUTRAL_MINERAL_FIELD750,
    Units.NEUTRAL_PURIFIER_MINERAL_FIELD,
    Units.NEUTRAL_PURIFIER_MINERAL_FIELD750,
    Units.NEUTRAL_PURIFIER_RICH_MINERAL_FIELD,
    Units.NEUTRAL_PURIFIER_RICH_MINERAL_FIELD750,
    Units.NEUTRAL_RICH_MINERAL_FIELD,
    Units.NEUTRAL_RICH_MINERAL_FIELD750,
    Units.NEUTRAL_MINERAL_FIELD_OPAQUE,
    Units.NEUTRAL_MINERAL_FIELD_OPAQUE900
)

val vespeneGasTypes = setOf(
    Units.NEUTRAL_PROTOSS_VESPENE_GEYSER,
    Units.NEUTRAL_PURIFIER_VESPENE_GEYSER,
    Units.NEUTRAL_RICH_VESPENE_GEYSER,
    Units.NEUTRAL_SHAKURAS_VESPENE_GEYSER,
    Units.NEUTRAL_VESPENE_GEYSER,
    Units.NEUTRAL_SPACE_PLATFORM_GEYSER

)

